### ISSUE TITLE
Support for Expo 52 and React Native 0.76 with New Architecture

### ISSUE THREAD

**Issue by dlee** [Kudo/react-native-v8#212]
Currently, react-native-v8 fails to compile with Expo 52 and React Native 0.76 with errors like this:

```
> Task :react-native-v8:configureCMakeRelWithDebInfo[arm64-v8a] FAILED
C/C++: CMake Error at CMakeLists.txt:42 (add_library):
C/C++:   Target "v8executor" links to target "ReactAndroid::folly_runtime" but the
C/C++:   target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:42 (add_library):
C/C++:   Target "v8executor" links to target "ReactAndroid::glog" but the target was
C/C++:   not found.  Perhaps a find_package() call is missing for an IMPORTED
C/C++:   target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:42 (add_library):
C/C++:   Target "v8executor" links to target "ReactAndroid::jsinspector" but the
C/C++:   target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:42 (add_library):
C/C++:   Target "v8executor" links to target "ReactAndroid::reactnativejni" but the
C/C++:   target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:42 (add_library):
C/C++:   Target "v8executor" links to target "ReactAndroid::runtimeexecutor" but the
C/C++:   target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:42 (add_library):
C/C++:   Target "v8executor" links to target "ReactAndroid::folly_runtime" but the
C/C++:   target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:42 (add_library):
C/C++:   Target "v8executor" links to target "ReactAndroid::glog" but the target was
C/C++:   not found.  Perhaps a find_package() call is missing for an IMPORTED
C/C++:   target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:42 (add_library):
C/C++:   Target "v8executor" links to target "ReactAndroid::reactnativejni" but the
C/C++:   target was not found.  Perhaps a find_package() call is missing for an
C/C++:   IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:84 (add_library):
C/C++:   Target "reactnative_internal_static" links to target
C/C++:   "ReactAndroid::folly_runtime" but the target was not found.  Perhaps a
C/C++:   find_package() call is missing for an IMPORTED target, or an ALIAS target
C/C++:   is missing?
C/C++: CMake Error at CMakeLists.txt:84 (add_library):
C/C++:   Target "reactnative_internal_static" links to target "ReactAndroid::glog"
C/C++:   but the target was not found.  Perhaps a find_package() call is missing for
C/C++:   an IMPORTED target, or an ALIAS target is missing?
C/C++: CMake Error at CMakeLists.txt:84 (add_library):
C/C++:   Target "reactnative_internal_static" links to target
C/C++:   "ReactAndroid::reactnativejni" but the target was not found.  Perhaps a
C/C++:   find_package() call is missing for an IMPORTED target, or an ALIAS target
C/C++:   is missing?
C/C++: CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by uonuon** [comment]
Any updates on this i still facing the same issue

**Comment by victor7w7r** [comment]
in iOS works, but in Android these errors appears, please help

**Comment by roadmanfong** [comment]
same issue, please help

**Comment by roadmanfong** [comment]
Hi, I'm currently encountering an issue with React Native V8 and Expo SDK 52.
To help illustrate the problem, I’ve put together a minimal reproducible example:
https://github.com/roadmanfong/expo-52-react-native-v8-example

**Comment by roadmanfong** [comment]
https://github.com/roadmanfong/expo-52-react-native-v8-example/pull/2

Finally I use expo prebuild and AI to make the project compiled successfully,
but it still have some issues.

it shows error.

```
	Process: com.roadmanfong.expo52demo, PID: 12687
	com.facebook.soloader.SoLoaderDSONotFoundError: couldn't find DSO to load: libjsctooling.so
		existing SO sources: 
			SoSource 0: ApplicationSoSource[DirectorySoSource[root = /data/app/~~9xUV7u4l2o2N5Iiu3__JhA==/com.roadmanfong.expo52demo-PKT9Bi1ZBgFJPZUI5my6gw==/lib/arm64 flags = 0]]
			SoSource 1: DirectApkSoSource[root = [/data/app/~~9xUV7u4l2o2N5Iiu3__JhA==/com.roadmanfong.expo52demo-PKT9Bi1ZBgFJPZUI5my6gw==/base.apk!/lib/arm64-v8a]]
			SoSource 2: DirectorySoSource[root = /system/lib64 flags = 3]
			SoSource 3: DirectorySoSource[root = /vendor/lib64 flags = 3]
		Native lib dir: /data/app/~~9xUV7u4l2o2N5Iiu3__JhA==/com.roadmanfong.expo52demo-PKT9Bi1ZBgFJPZUI5my6gw==/lib/arm64
	
		at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1216)
		at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:1078)
		at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:943)
		at com.facebook.soloader.SoLoader.loadLibraryOnAndroid(SoLoader.java:859)
		at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:842)
		at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:812)
		at com.facebook.react.runtime.JSCInstance.<clinit>(JSCInstance.kt:19)
		at expo.modules.ExpoReactHostFactory$ExpoReactHostDelegate.getJsRuntimeFactory(ExpoReactHostFactory.kt:66)
		at com.facebook.react.runtime.ReactInstance.<init>(ReactInstance.java:146)
		at com.facebook.react.runtime.ReactHostImpl.lambda$getOrCreateReactInstanceTask$22(ReactHostImpl.java:1118)
		at com.facebook.react.runtime.ReactHostImpl.$r8$lambda$sX0vNfk_MttxfVwE2w9ALnXHrPI(Unknown Source:0)
		at com.facebook.react.runtime.ReactHostImpl$$ExternalSyntheticLambda43.then(D8$$SyntheticClass:0)
		at com.facebook.react.runtime.internal.bolts.Task$7.run(Task.java:423)
		at com.facebook.react.runtime.internal.bolts.Executors$ImmediateExecutor.execute(Executors.kt:41)
		at com.facebook.react.runtime.internal.bolts.Task.completeImmediately(Task.java:418)
		at com.facebook.react.runtime.internal.bolts.Task.continueWith(Task.java:288)
		at com.facebook.react.runtime.internal.bolts.Task.continueWith(Task.java:299)
		at com.facebook.react.runtime.internal.bolts.Task$5.then(Task.java:354)
		at com.facebook.react.runtime.internal.bolts.Task$5.then(Task.java:346)
		at com.facebook.react.runtime.internal.bolts.Task$8.run(Task.java:460)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
		at java.lang.Thread.run(Thread.java:1119)
		
```

**Comment by gauravgautamapptile** [comment]
Same issue on 0.77. Is this library no longer supported?

**Comment by rohitx15** [comment]
Also same issue -- expo sdk 52 react-native 0.77
