### ISSUE TITLE
Crashing when used with Realm

### ISSUE THREAD

**Issue by ItsNoHax** [Kudo/react-native-v8#26]
RN: 0.59.10
V8: 7.5.1
react-native-v8: 0.59.10-patch.2

App is crashing directly on start up due to the following error:
```
2019-10-14 10:43:22.700 7843-7902/? E/SoLoader: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: library "libjsc.so" not found
2019-10-14 10:43:22.701 7843-7902/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: nl.basenet.appreactnative, PID: 7843
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: librealmreact.so caused by: dlopen failed: library "libjsc.so" not found
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at io.realm.react.RealmReactModule.<clinit>(RealmReactModule.java:56)
        at io.realm.react.RealmReactPackage.createNativeModules(RealmReactPackage.java:31)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
        at java.lang.Thread.run(Thread.java:919)
```

Our app would really benefit from using the V8 library as we really prioritise performance. What could I do to get this working with Realm?

**Comment by ItsNoHax** [comment]
Going to close this issue as it's really an issue on Realm's side. Issue can be followed here: https://github.com/realm/realm-js/issues/2455
