### ISSUE TITLE
[V8 + expo bare] SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by RodolfoGS** [Kudo/react-native-v8#63]
Hi, I'm trying to migrate to V8 engine since I read awesome reviews regarding the performance.

Currently I have a project with Expo Bare workflow and I'm trying to implement v8.
I followed the readme to implement it and works great, when I run my app in debug mode all works as expected, perfectly.
But when I create a release APK, when the app is starting I'm getting the following crash. Someone know what could be happening?

Thanks,

```
2021-02-26 22:04:01.807 16264-16327/? E/unknown:ReactNative: ReactInstanceManager.createReactContext: mJSIModulePackage null
2021-02-26 22:04:01.807 16264-16346/? E/ReactNativeJNI: logMarker CREATE_REACT_CONTEXT_END
2021-02-26 22:04:01.876 16264-16346/? E/ReactNativeJNI: logMarker RUN_JS_BUNDLE_START
2021-02-26 22:04:01.880 16264-16348/? E/unknown:ReactNative: ReactInstanceManager.attachRootViewToInstance()
2021-02-26 22:04:01.901 13487-11479/? E/NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=1s,earliest=-92s,latest=-91s} requirements=[NET_CONNECTED] attributes=[PERSISTED] scheduled=-92s last_run=-92s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-210214000} :1 [CONTEXT service_id=218 ]
2021-02-26 22:04:01.956 16264-16346/? E/unknown:ReactNative: CatalystInstanceImpl caught native exception
    com.facebook.react.devsupport.JSException: index.android.bundle:1: SyntaxError: Invalid or unexpected token
    ���J
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.jni.CppException: index.android.bundle:1: SyntaxError: Invalid or unexpected token
    ���J
        ... 7 more
2021-02-26 22:04:01.956 16264-16346/? E/unknown:DisabledDevSupportManager: Caught exception
    com.facebook.react.devsupport.JSException: index.android.bundle:1: SyntaxError: Invalid or unexpected token
    ���J
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.jni.CppException: index.android.bundle:1: SyntaxError: Invalid or unexpected token
    ���J
        ... 7 more
    
    
    --------- beginning of crash
2021-02-26 22:04:01.957 16264-16346/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.x.x, PID: 16264
    java.lang.RuntimeException: com.facebook.react.devsupport.JSException: index.android.bundle:1: SyntaxError: Invalid or unexpected token
    ���J
        at com.facebook.react.bridge.DefaultNativeModuleCallExceptionHandler.handleException(DefaultNativeModuleCallExceptionHandler.java:20)
        at com.facebook.react.devsupport.DisabledDevSupportManager.handleException(DisabledDevSupportManager.java:164)
        at com.facebook.react.bridge.CatalystInstanceImpl.onNativeException(CatalystInstanceImpl.java:721)
        at com.facebook.react.bridge.CatalystInstanceImpl.access$1300(CatalystInstanceImpl.java:47)
        at com.facebook.react.bridge.CatalystInstanceImpl$NativeExceptionHandler.handleException(CatalystInstanceImpl.java:739)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.facebook.react.devsupport.JSException: index.android.bundle:1: SyntaxError: Invalid or unexpected token
    ���J
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
            ... 3 more
     Caused by: com.facebook.jni.CppException: index.android.bundle:1: SyntaxError: Invalid or unexpected token
    ���J
        ... 7 more
2021-02-26 22:04:02.018 16264-16348/? E/unknown:ReactRootView: runApplication: call AppRegistry.runApplication
2021-02-26 22:04:02.459 13487-13793/? E/NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=1s,earliest=-92s,latest=-91s} requirements=[NET_CONNECTED] attributes=[PERSISTED] scheduled=-92s last_run=-92s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-210214000} :1 [CONTEXT service_id=218 ]
2021-02-26 22:04:02.529 13487-13793/? E/NetworkScheduler.ATC: Called cancelTask for already completed task com.google.android.gms/.measurement.PackageMeasurementTaskService{u=0 tag="Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG" trigger=window{start=0s,end=1s,earliest=-92s,latest=-91s} requirements=[NET_CONNECTED] attributes=[PERSISTED] scheduled=-92s last_run=-92s exec_window_multiplier=1.0000 jid=N/A status=ACTIVE retries=0 client_lib=GMS_TASK_SCHEDULER-210214000} :1 [CONTEXT service_id=218 ]
```

I'm using:
```
react-native: 0.63.4
react-native-v8: 0.63.4-patch.1
expo: 40.0.1
expo-asset: 8.2.2
expo-background-fetch: 9.0.0
expo-constants: 10.0.1
expo-font: 9.0.0
expo-notifications: 0.9.0
expo-permissions: 11.0.0
expo-secure-store: 10.0.0
expo-splash-screen: 0.9.0
expo-sqlite: 9.0.0
expo-task-manager: 9.0.0
expo-updates: 0.4.1
```

**Comment by Kudo** [comment]
Did you try to clean build or removing build folder first?
Looks like the generated bundle is not a valid JavaScript bundle, sometimes it might be a Hermes generated bytecode bundle.

**Comment by RodolfoGS** [comment]
Hi @Kudo, thanks for your response. I just already clean the project (Android Studio -> Build -> Clean Project) and run this command: `cd android && ./gradlew clean`

But I'm continue having the crash, I don't know what could be happening

**Comment by RodolfoGS** [comment]
I notice that I'm getting this error when I run: `cd android && ./gradlew clean`. I already deleted node_modules but nothing changed, same issue.

```
cd android/ && ./gradlew clean

FAILURE: Build failed with an exception.

* Where:
Script '/xx/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 231

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /xx/node_modules/react-native/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

  The current character read is 'E' with an int value of 69
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  Error: Non-whitespace before first tag.Line: 0Column: 1Char:     at error (/xx/node_modules/sax/lib/sax.js:651:10)    at strictFail (/xx/node_modules/sax/lib/sax.js:677:7)    at beginWhiteSpace (/xx/node_modules/sax/lib/sax.js:951:7)    at SAXParser.write (/xx/node_modules/sax/lib/sax.js:1006:11)    at new XmlDocument (/xx/node_modules/xmldoc/lib/xmldoc.js:261:15)    at readManifest (/xx/node_modules/@react-native-community/cli-platform-android/build/config/readManifest.js:38:10)    at Object.projectConfig (/xx/node_modules/@react-native-community/cli-platform-android/build/config/index.js:70:46)    at Object.get project [as project] (/xx/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/config/index.js:106:50)    at filterConfig (/xx/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:13:20)    at Object.func (/xx/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:27:32)
  ^. Output: Error: Non-whitespace before first tag.Line: 0Column: 1Char:     at error (/xx/node_modules/sax/lib/sax.js:651:10)    at strictFail (/xx/node_modules/sax/lib/sax.js:677:7)    at beginWhiteSpace (/xx/node_modules/sax/lib/sax.js:951:7)    at SAXParser.write (/xx/node_modules/sax/lib/sax.js:1006:11)    at new XmlDocument (/xx/node_modules/xmldoc/lib/xmldoc.js:261:15)    at readManifest (/xx/node_modules/@react-native-community/cli-platform-android/build/config/readManifest.js:38:10)    at Object.projectConfig (/xx/node_modules/@react-native-community/cli-platform-android/build/config/index.js:70:46)    at Object.get project [as project] (/xx/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/config/index.js:106:50)    at filterConfig (/xx/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:13:20)    at Object.func (/xx/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:27:32)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
<-------------> 0% WAITING
> IDLE
```

**Comment by Kudo** [comment]
The new error from gradle looks weird. maybe you could double check what `build/bin.js, config` doing.

Please also makes sure `enableHermes` as false [here](https://github.com/facebook/react-native/blob/master/template/android/app/build.gradle#L121) in your build.gradle.

**Comment by RodolfoGS** [comment]
I had `enableHermes` on true, I changed it but I'm continue having the same issue with `gradlew clean`.

Where is the `build/bin.js, config` file?, I doesn't have it

**Comment by Kudo** [comment]
build/bin.js config is from your error message
`Calling `[node, /xx/node_modules/react-native/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object`

Probably to cleanup node_modules and reinstall all modules again?

**Comment by RodolfoGS** [comment]
I made that but didn't work, same result. The rare is that when I run as develop the app works, the crash only appears when I create a release APK.
I tried to create a minimal reproducible example but with a new project works as expected, so it seems that is an issue with (maybe) same library that I'm using, I don't know

**Comment by Kudo** [comment]
You have to set enableHermes as false. Otherwise, the generated JS bundle will be Hermes bytecode bundle.

**Comment by RodolfoGS** [comment]
Yes, I did that. I disabled Hermes, removed node_modules, clean build folder, sync, removed .gradle and .idea folders, npx jetify... nothing, doesn't work 😔

**Comment by Kudo** [comment]
Could you double check the content of index.android.bundle?
E.g. This is output of Hermes bundle
```sh
$ file android/app/build/generated/assets/react/release/index.android.bundle
android/app/build/generated/assets/react/release/index.android.bundle: data
```

This is normal JS bundle
```sh
$ file android/app/build/generated/assets/react/release/index.android.bundle
android/app/build/generated/assets/react/release/index.android.bundle: ASCII text, with very long lines
```

**Comment by RodolfoGS** [comment]
Hey @Kudo, thank you so much for your help! Finally I could fix the issue. I see the bundle generated into the APK (index.android.bundle) and was a binary file. So, seems that Android Studio was continue building the project with Hermes enabled even though it was in false.
I made every thing to clean the cache. Clean project, remove node_modules, Invalid cache / restart Android Studio.. all and finally it's working! 🎉

Again, thank you so much for your help, you are great! 🙌

I'll close the issue, if someone have the same issue. Just disable Hermes and reset the cache of all you can 😅
