### ISSUE TITLE
RN 0.64 - dlopen failed: library "libjsc.so" not found

### ISSUE THREAD

**Issue by xRiot** [Kudo/react-native-v8#71]
Hey there!

We've setup our react-native project with the [react-native-template-typescript](https://github.com/react-native-community/react-native-template-typescript) and we're using [react-native-reanimated@2.2.0](https://github.com/software-mansion/react-native-reanimated). It looks like `0.64.0-patch.0` isn't working with reanimated due to `libjsc.so` being excluded in `packagingOptions` as instructed by the README:

```bash
2021-06-01 17:17:52.898 16888-17612/com.testapp E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.testapp, PID: 16888
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found: needed by /data/app/~~f11IRWbIPWNh9lR7rLgb1w==/com.testapp-JXXVu5SfxC7E-nrBFfYAqQ==/lib/arm64/libjscexecutor.so in namespace classloader-namespace
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.swmansion.reanimated.NativeProxy.<clinit>(NativeProxy.java:22)
        at com.swmansion.reanimated.NodesManager.initWithContext(NodesManager.java:127)
        at com.swmansion.reanimated.ReanimatedJSIModulePackage.getJSIModules(ReanimatedJSIModulePackage.java:18)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1265)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
        at java.lang.Thread.run(Thread.java:923)
```

Any clues how we could resolve this issue? Any tips are welcome!

**Comment by Kudo** [comment]
sorry that reanimated does not support v8 in the meantime.
it's a known issue as #64.
